version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth:
    build:
      context: ../apps/auth
      dockerfile: Dockerfile
    container_name: auth
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/ecommerce
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "3001:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  mongo_data:
