apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: ecommerce
data:
  # MongoDB Configurations
  MONGO_INITDB_DATABASE: "admin"
  MONGO_INITDB_ROOT_USERNAME: "admin"
  
  # MongoDB Replica Set Configuration (optional)
  replica-set-name: "rs0"

